import type { Metadata } from "next";

import "./globals.css";
// import { Poppins } from "next/font/google";
// import { Geist, Geist_Mono } from "next/font/google";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700;800&display=swap" rel="stylesheet" />

// export const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600"],
//   variable: "--font-poppins",
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Sync And Explore",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg", // path to your favicon in public/
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
